# Generated by Django 5.0.1 on 2024-02-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_watched_movies',
            name='movie_name',
            field=models.TextField(),
        ),
    ]
