# Generated by Django 5.0.1 on 2024-03-05 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_alter_my_watched_movies_movie_name'),
        ('MovieApp', '0003_alter_my_watched_movies_tier'),
    ]

    operations = [
    ]
