# Generated by Django 5.0.1 on 2024-03-05 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0004_merge_20240305_0308'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_watched_movies',
            name='tier',
            field=models.TextField(default='N', null=True),
        ),
        migrations.CreateModel(
            name='My_Tier_Lists',
            fields=[
                ('tier_list_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tier_list_name', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='my_watched_movies',
            name='tier_list_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieApp.my_tier_lists'),
        ),
    ]
