# Generated by Django 5.0.1 on 2024-03-09 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0006_remove_my_watched_movies_tier_list_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Tier_Lists',
            fields=[
                ('tier_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='My_Watched_Movies',
            fields=[
                ('watched_movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieApp.popular_movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tier_List_Watched_Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_ranking_row', models.IntegerField()),
                ('tier_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieApp.my_tier_lists')),
                ('watched_movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieApp.my_watched_movies')),
            ],
        ),
    ]
