# Generated by Django 5.0.1 on 2024-03-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0008_alter_tier_list_watched_movies_tier_ranking_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular_movies',
            name='popularity',
            field=models.IntegerField(default=0, max_length=140),
        ),
    ]
