# Generated by Django 5.0.1 on 2024-03-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0009_popular_movies_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular_movies',
            name='budget',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popular_movies',
            name='revenue',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popular_movies',
            name='runtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popular_movies',
            name='tagline',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='popular_movies',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
